[build]
  base = "web"
  command = "CI=false npm install && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

