[build]
  base = "web"
  command = "npm ci --legacy-peer-deps && npm run build:ci"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

